Repository davidmigloz/langchain_dart, pull requests merged in 2025-03, with the labels that each got.

#671 fix: Issue labeling workflow missing write permissions
  .github/workflows/label-issue.yaml
Labels: t:bug

#672 docs: Update issue templates to include relevant package
  .github/ISSUE_TEMPLATE/1_feature.yml
  .github/ISSUE_TEMPLATE/2_bug.yml
Labels: t:documentation

#678 build: Run Deploy docs_v2 workflow only if docs_v2 files changed
  .github/workflows/firebase-hosting-merge.yml
Labels: t:documentation

#668 Fix: Server VAD is enabled after setting turnDetection to null
  packages/openai_realtime_dart/lib/src/client.dart
  packages/openai_realtime_dart/lib/src/schema/generated/schema/schema.freezed.dart
  packages/openai_realtime_dart/lib/src/schema/generated/schema/schema.g.dart
  packages/openai_realtime_dart/lib/src/schema/generated/schema/session_config.dart
  packages/openai_realtime_dart/oas/openai_spec_curated.yaml
Labels: t:bug, p:openai_realtime_dart

#680 build: Group dependabot PRs
  .github/dependabot.yml
Labels: dependencies

#681 feat: Add to/fromMap serialization to ChatMessage, PromptValue & ChatHistory
  packages/langchain/lib/src/chat_history/in_memory.dart
  packages/langchain_core/lib/src/chat_models/types.dart
  packages/langchain_core/lib/src/prompts/types.dart
  packages/langchain_core/test/chat_models/types.dart
Labels: t:enhancement, p:langchain
